Thu, 12 Jul 2018 11:02:23 connectionpool.py[line:824] DEBUG Starting new HTTPS connection (1): hupai.pro
Thu, 12 Jul 2018 11:02:24 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/get_guopaiurl/?format=json&type=identify_code&debug=True&version=5.3&identify_code=12345678&diskid=dca984ffb6ff32225862a03946345c2c073097c1 HTTP/1.1" 200 None
Thu, 12 Jul 2018 11:02:24 app_thread.py[line:811] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 806, in run
    if start_time < a_time < target_time:  ##11点到11点半之间
TypeError: '<' not supported between instances of 'str' and 'float'
Thu, 12 Jul 2018 11:02:24 imgcut.py[line:268] ERROR cut_img 这里出错
Thu, 12 Jul 2018 11:02:25 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 261, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:25 app_thread.py[line:224] ERROR 刷新失败
Thu, 12 Jul 2018 11:02:25 app_thread.py[line:225] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 222, in find_refresh
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 277, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 12 Jul 2018 11:02:25 app_thread.py[line:811] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 806, in run
    if start_time < a_time < target_time:  ##11点到11点半之间
TypeError: '<' not supported between instances of 'str' and 'float'
Thu, 12 Jul 2018 11:02:25 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:25 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 359, in Price_read
    lowest_price_img = cv2.cvtColor(imgpos_lowestprice, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 12 Jul 2018 11:02:25 connectionpool.py[line:208] DEBUG Starting new HTTP connection (1): ip.taobao.com
Thu, 12 Jul 2018 11:02:25 connectionpool.py[line:396] DEBUG http://ip.taobao.com:80 "GET /service/getIpInfo.php?ip=101.87.250.19 HTTP/1.1" 200 None
Thu, 12 Jul 2018 11:02:25 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:25 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 245, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Thu, 12 Jul 2018 11:02:26 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:26 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 245, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Thu, 12 Jul 2018 11:02:26 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:26 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 245, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Thu, 12 Jul 2018 11:02:27 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:27 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:27 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:27 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:27 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:27 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:28 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:29 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:29 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:29 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:29 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 12 Jul 2018 11:02:29 app_thread.py[line:256] ERROR 识别价格失败
Thu, 12 Jul 2018 11:02:29 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
