Sat, 23 Jun 2018 15:53:18 app_thread.py[line:193] ERROR 截图失败
Sat, 23 Jun 2018 15:53:18 app_thread.py[line:194] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 188, in run_func
    cut_img()
  File "E:\hupai\component\imgcut.py", line 453, in cut_img
    img = only_screenshot(sc_area)  # 获取得到的截图
  File "E:\hupai\component\imgcut.py", line 434, in only_screenshot
    dataBitMap.CreateCompatibleBitmap(dcObj, w - x, h - y)
win32ui.error: CreateCompatibleDC failed
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:19 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:19 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:20 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:20 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:20 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:20 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Sat, 23 Jun 2018 15:53:20 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:256] ERROR 识别价格失败
Sat, 23 Jun 2018 15:53:20 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
