Tue, 13 Mar 2018 09:35:21 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Tue, 13 Mar 2018 09:35:21 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 65536
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:21 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:21 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:21 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:22 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:22 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:22 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:23 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:23 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:24 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:24 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:24 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:25 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:25 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:25 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:26 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:26 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:26 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:27 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:27 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:27 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Tue, 13 Mar 2018 09:35:27 imgcut.py[line:309] ERROR cut_img 这里出错
Tue, 13 Mar 2018 09:35:27 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:109] ERROR 刷新失败
Tue, 13 Mar 2018 09:35:27 app_thread.py[line:110] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 107, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

