Thu, 21 Jun 2018 18:51:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 218, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Thu, 21 Jun 2018 18:51:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:51:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:51:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:49 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:49 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:49 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:49 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 243, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:50 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:50 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 243, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:51 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:51 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 243, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:52 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:52 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 243, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Thu, 21 Jun 2018 18:52:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:255] ERROR 识别价格失败
Thu, 21 Jun 2018 18:52:53 app_thread.py[line:256] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 235, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 539, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
