Tue, 17 Jul 2018 09:12:27 connectionpool.py[line:824] DEBUG Starting new HTTPS connection (1): hupai.pro
Tue, 17 Jul 2018 09:12:28 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/get_guopaiurl/?format=json&type=identify_code&debug=True&version=5.4&identify_code=h54988437&diskid=dca984ffb6ff32225862a03946345c2c073097c1 HTTP/1.1" 200 None
Tue, 17 Jul 2018 09:12:29 app_thread.py[line:812] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 807, in run
    if start_time < a_time < target_time:  ##11点到11点半之间
TypeError: '<' not supported between instances of 'str' and 'float'
Tue, 17 Jul 2018 09:12:29 connectionpool.py[line:208] DEBUG Starting new HTTP connection (1): ip.taobao.com
Tue, 17 Jul 2018 09:12:29 imgcut.py[line:272] ERROR cut_img 这里出错
Tue, 17 Jul 2018 09:12:29 imgcut.py[line:273] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 265, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:29 app_thread.py[line:225] ERROR 刷新失败
Tue, 17 Jul 2018 09:12:29 app_thread.py[line:226] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 223, in find_refresh
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 281, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 17 Jul 2018 09:12:29 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:29 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 367, in Price_read
    lowest_price_img = cv2.cvtColor(imgpos_lowestprice, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 17 Jul 2018 09:12:29 connectionpool.py[line:396] DEBUG http://ip.taobao.com:80 "GET /service/getIpInfo.php?ip=101.87.221.219 HTTP/1.1" 200 None
Tue, 17 Jul 2018 09:12:29 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:29 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 245, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Tue, 17 Jul 2018 09:12:31 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:31 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:32 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:33 imgcut.py[line:104] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:33 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:33 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:33 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:33 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:45 imgcut.py[line:104] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:45 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 271, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 271, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 271, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 271, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 271, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:46 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 271, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Tue, 17 Jul 2018 09:12:49 connectionpool.py[line:824] DEBUG Starting new HTTPS connection (1): hupai.pro
Tue, 17 Jul 2018 09:12:49 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/get_remotetime HTTP/1.1" 301 0
Tue, 17 Jul 2018 09:12:49 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/get_remotetime/ HTTP/1.1" 200 33
Tue, 17 Jul 2018 09:12:50 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:50 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:51 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:52 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:53 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:54 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:55 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:56 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:57 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:58 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:12:59 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:00 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:01 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:01 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:01 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:01 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:01 app_thread.py[line:257] ERROR 识别价格失败
Tue, 17 Jul 2018 09:13:01 app_thread.py[line:258] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 237, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 368, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Tue, 17 Jul 2018 09:13:03 connectionpool.py[line:824] DEBUG Starting new HTTPS connection (1): hupai.pro
Tue, 17 Jul 2018 09:13:03 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/bid_logout/?type=identify_code&identify_code=h54988437&diskid=dca984ffb6ff32225862a03946345c2c073097c1&strategy_dick=%7B%220%22:%20[%220%22,%2050.0,%20700,%200,%200.5,%2055.0,%20true,%20true,%2050.0,%20700,%20100,%200.5,%2056.0,%20true,%200,%200,%2054.0,%20100,%200.6,%2055,%20200,%200.5,%2056.0,%2056.5],%20%221%22:%20[%221%22,%2040.0,%20500,%200,%200.5,%2048.0,%20true,%20true,%2050.0,%20700,%20100,%200.5,%2056.0,%20true,%200,%200,%2054.0,%20100,%200.6,%2055,%20200,%200.5,%2056.0,%2056.5],%20%222%22:%20[%222%22,%2050.0,%20700,%200,%200.5,%2055.0,%20true,%20true,%2050.0,%20700,%20100,%200.5,%2056.0,%20true,%200,%200,%2054.0,%20100,%200.6,%2055,%20200,%200.5,%2056.0,%2056.5],%20%223%22:%20[%223%22,%2035.0,%20400,%200,%200.0,%2043.0,%20true,%20true,%2045.0,%201100,%20100,%200.5,%2056.0,%20true,%200.0,%200.0,%2053.0,%20100.0,%200.5,%2054.0,%20100.0,%200.1,%2055.0,%2055.6],%20%224%22:%20[%224%22,%2040.0,%20500,%200,%200.5,%2048.0,%20true,%20true,%2050.0,%20700,%20100,%200.5,%2056.0,%20true,%200,%200,%2054.0,%20100,%200.6,%2055,%20200,%200.5,%2056.0,%2056.5],%20%22yanzhengma_scale%22:%20true,%20%22strategy_description%22:%20%22%5Cu53cc%5Cu67aa%5Cu52a8%5Cu6001%20%2035.0%5Cu79d2%5Cu52a0400%5Cu51fa%5Cu4ef7%20%2045.0%5Cu79d2%5Cu52a01100%5Cu51fa%5Cu4ef7%22,%20%22strategy_type%22:%20%223%22,%20%22enter_on%22:%20true%7D&account=%7B%22account%22:%20%2254988437%22,%20%22password%22:%20%221554%22,%20%22idcard%22:%20%22310225197904010037%22%7D HTTP/1.1" 200 27
