Fri, 27 Apr 2018 10:56:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Fri, 27 Apr 2018 10:56:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 65536
Fri, 27 Apr 2018 10:56:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Fri, 27 Apr 2018 10:56:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 65536
Fri, 27 Apr 2018 10:56:28 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:29 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:30 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:31 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:32 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:33 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:34 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:35 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:36 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:37 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:38 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:39 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:40 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:41 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:42 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:43 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:44 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:45 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:46 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:47 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:48 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:49 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:50 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:51 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:52 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:53 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:54 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:55 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:56 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:57 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:58 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:56:59 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Fri, 27 Apr 2018 10:57:00 imgcut.py[line:269] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 239, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

