Mon, 09 Jul 2018 14:16:41 connectionpool.py[line:824] DEBUG Starting new HTTPS connection (1): hupai.pro
Mon, 09 Jul 2018 14:16:42 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/get_guopaiurl/?format=json&type=identify_code&debug=True&version=5.1&identify_code=h55555555&diskid=dca984ffb6ff32225862a03946345c2c073097c1 HTTP/1.1" 200 None
Mon, 09 Jul 2018 14:16:42 connectionpool.py[line:208] DEBUG Starting new HTTP connection (1): ip.taobao.com
Mon, 09 Jul 2018 14:16:42 connectionpool.py[line:396] DEBUG http://ip.taobao.com:80 "GET /service/getIpInfo.php?ip=101.87.250.19 HTTP/1.1" 200 None
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:16:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:43 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:43 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 imgcut.py[line:102] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:44 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 imgcut.py[line:102] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:45 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 imgcut.py[line:102] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:46 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 imgcut.py[line:102] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:47 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:48 imgcut.py[line:102] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 91, in timeset
    currenttime = readpic(currenttime)  # 识别出来的时间
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:256] ERROR 识别价格失败
Mon, 09 Jul 2018 14:17:48 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 363, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 265, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 97, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 09 Jul 2018 14:17:52 imgcut.py[line:102] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 96, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-07-09 000000000' does not match format '%Y-%m-%d %H:%M:%S'
