Sun, 06 May 2018 21:13:24 PngImagePlugin.py[line:138] DEBUG STREAM b'IHDR' 16 13
Sun, 06 May 2018 21:13:24 PngImagePlugin.py[line:138] DEBUG STREAM b'IDAT' 41 65536
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:26 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:26 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:26 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:26 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:27 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:27 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:27 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:27 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:28 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:28 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:28 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:28 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:28 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:28 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:28 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:28 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:28 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:28 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:28 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 imgcut.py[line:270] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 240, in timeset
    currenttime = cv2.cvtColor(imgpos_currenttime, cv2.COLOR_BGR2GRAY)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 imgcut.py[line:404] ERROR cut_img 这里出错
Sun, 06 May 2018 21:13:28 imgcut.py[line:405] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 390, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Sun, 06 May 2018 21:13:28 app_thread.py[line:149] ERROR 刷新失败
Sun, 06 May 2018 21:13:28 app_thread.py[line:150] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 147, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 419, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:28 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:28 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:28 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:270] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 242, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 226, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 167, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:29 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:29 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:29 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:30 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:30 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:30 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:31 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:31 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:31 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:32 imgcut.py[line:396] INFO 截图成功
Sun, 06 May 2018 21:13:32 imgcut.py[line:398] INFO imgpos_yanzhengma 43:153, 358:538
Sun, 06 May 2018 21:13:32 imgcut.py[line:400] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Sun, 06 May 2018 21:13:32 imgcut.py[line:396] INFO 截图成功
