Fri, 11 May 2018 20:23:03 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:03 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:03 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:03 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:03 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:03 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:04 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:04 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:04 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:05 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:05 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:05 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:05 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 app_thread.py[line:227] ERROR 识别价格失败
Fri, 11 May 2018 20:23:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 510, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:06 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:06 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:06 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:07 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:07 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:07 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 3680' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:08 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:08 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:08 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Fri, 11 May 2018 20:23:09 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-11 88444' does not match format '%Y-%m-%d %H:%M:%S'
Fri, 11 May 2018 20:23:09 imgcut.py[line:435] INFO 截图成功
Fri, 11 May 2018 20:23:09 imgcut.py[line:437] INFO imgpos_yanzhengma 43:153, 358:538
Fri, 11 May 2018 20:23:09 imgcut.py[line:439] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
