Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:37 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:37 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:37 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:38 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:38 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:38 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:38 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:38 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:39 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:39 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:39 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:39 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:40 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:40 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:40 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:41 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:41 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:41 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:42 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:42 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:42 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:43 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:43 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:43 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:43 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:43 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:44 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:44 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:44 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:44 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:44 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:45 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:45 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:45 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:45 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:45 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:46 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:46 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:46 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:46 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:46 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:46 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:47 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:47 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:47 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:48 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:48 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:48 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:48 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:48 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:48 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:48 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:48 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:48 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:48 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: ':81800'
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: ':81800'
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: ':81800'
Mon, 21 May 2018 11:19:49 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 :11:29:01' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: ':81800'
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:49 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
ValueError: invalid literal for int() with base 10: ':81800'
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:49 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:49 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:49 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:50 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:50 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:50 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:51 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:51 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:51 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:52 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:52 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:52 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:53 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:53 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:53 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:54 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:54 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:54 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:55 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:55 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:55 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:56 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:56 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:56 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:57 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:57 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:57 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:57 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:58 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:58 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:58 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:58 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:58 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:19:59 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:19:59 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:19:59 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:19:59 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:19:59 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:00 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:00 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:00 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:00 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:00 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:01 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:01 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:01 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:20:01 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:01 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:01 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:02 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:02 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:02 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:02 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:02 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:02 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:02 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:02 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:02 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:02 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:03 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:03 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:03 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:03 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:03 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:03 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:03 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:03 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:04 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:04 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:04 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 app_thread.py[line:232] ERROR 截图失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 183, in run
    cut_img()
  File "E:\hupai\component\imgcut.py", line 425, in cut_img
    img = only_screenshot(sc_area)  # 获取得到的截图
  File "E:\hupai\component\imgcut.py", line 404, in only_screenshot
    dataBitMap.CreateCompatibleBitmap(dcObj, w - x, h - y)
win32ui.error: CreateCompatibleDC failed
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 241, in timeset
    currenttime = readpic(currenttime, maindata)  # 识别出来的时间
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:05 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:05 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:05 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:05 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:05 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 app_thread.py[line:227] ERROR 识别价格失败
Mon, 21 May 2018 11:20:06 app_thread.py[line:228] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    price = int(Price_read())  # 获取当前最低价
  File "E:\hupai\component\imgcut.py", line 512, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 225, in readpic
    testData = cut(img)
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:06 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:06 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:06 imgcut.py[line:255] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 249, in timeset
    a_time_temp = time.mktime(time.strptime(b, '%Y-%m-%d %H:%M:%S')) + 0.6  # 转时间戳   补个平均时差
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\Administrator\Python\Python36\Lib\_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-05-21 44444' does not match format '%Y-%m-%d %H:%M:%S'
Mon, 21 May 2018 11:20:07 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:07 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:07 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Mon, 21 May 2018 11:20:07 imgcut.py[line:434] INFO 截图成功
Mon, 21 May 2018 11:20:07 imgcut.py[line:436] INFO imgpos_yanzhengma 43:153, 358:538
Mon, 21 May 2018 11:20:07 imgcut.py[line:438] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
