Fri, 13 Jul 2018 10:03:51 connectionpool.py[line:824] DEBUG Starting new HTTPS connection (1): hupai.pro
Fri, 13 Jul 2018 10:03:52 connectionpool.py[line:396] DEBUG https://hupai.pro:443 "GET /api/bid/get_guopaiurl/?format=json&type=identify_code&debug=True&version=5.3&identify_code=12345678&diskid=dca984ffb6ff32225862a03946345c2c073097c1 HTTP/1.1" 200 None
Fri, 13 Jul 2018 10:03:52 connectionpool.py[line:208] DEBUG Starting new HTTP connection (1): ip.taobao.com
Fri, 13 Jul 2018 10:03:52 connectionpool.py[line:396] DEBUG http://ip.taobao.com:80 "GET /service/getIpInfo.php?ip=101.87.218.43 HTTP/1.1" 200 None
Fri, 13 Jul 2018 10:03:53 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:53 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 245, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 13 Jul 2018 10:03:53 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:53 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 245, in cut
    imgn[i] = cv2.resize(imgn[i], (8, 8))
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Fri, 13 Jul 2018 10:03:53 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:53 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:53 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:53 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:256] ERROR 识别价格失败
Fri, 13 Jul 2018 10:03:54 app_thread.py[line:257] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 236, in read_lowest_price
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 360, in Price_read
    price = readpic(lowest_price_img)
  File "E:\hupai\component\read_pic.py", line 267, in readpic
    testData = cut(img)
  File "E:\hupai\component\read_pic.py", line 99, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
