Tue, 03 Apr 2018 22:02:33 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:02:33 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 1330
Tue, 03 Apr 2018 22:02:33 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:02:33 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 65536
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:33 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:33 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:33 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:33 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:33 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:33 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:33 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:34 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:34 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:34 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:35 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:35 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:35 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:36 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:36 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:36 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 imgcut.py[line:368] ERROR cut_img 这里出错
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 imgcut.py[line:369] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 361, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:02:37 app_thread.py[line:125] ERROR 刷新失败
Tue, 03 Apr 2018 22:02:37 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 383, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:24 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:25 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:26 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:27 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:28 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Tue, 03 Apr 2018 22:03:29 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
