Wed, 07 Mar 2018 16:56:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:04 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 65536
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:04 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:04 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:04 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:04 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:04 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:04 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:04 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:04 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:05 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:05 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:05 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:06 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:06 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:06 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:07 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:07 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:07 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:08 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:08 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:08 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:09 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:09 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:09 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 imgcut.py[line:310] ERROR cut_img 这里出错
Wed, 07 Mar 2018 16:56:10 imgcut.py[line:311] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\imgcut.py", line 303, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:10 app_thread.py[line:108] ERROR 刷新失败
Wed, 07 Mar 2018 16:56:10 app_thread.py[line:109] ERROR this is an exception message
Traceback (most recent call last):
  File "F:/BestAssistant\component\app_thread.py", line 106, in run
    findrefresh()
  File "F:/BestAssistant\component\imgcut.py", line 325, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:10600: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cv::cvtColor

Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 985
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:46 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:47 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:48 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:49 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IHDR' 16 13
Wed, 07 Mar 2018 16:56:50 PngImagePlugin.py[line:130] DEBUG STREAM b'IDAT' 41 8192
